"""new migration

Revision ID: d5ee9e3c6b18
Revises: d667ecd126cf
Create Date: 2023-06-26 16:34:24.161676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ee9e3c6b18'
down_revision = 'd667ecd126cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
